name: todo_time_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_native_splash: ^2.2.17
  flutter_native_timezone: ^2.0.0
  localstorage: ^4.0.0+1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.11.0

flutter_native_splash:
  color: "#000000"
  image: assets/icon.png
  android: true
  ios: true
  web: false
  android_12:
    image: assets/icon.png
    color: "#000000"

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "todo_time_app/assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
